### ISSUE TITLE
Using a real certificate from letsencrypt.org

### ISSUE THREAD

**Issue by chepurko** [ouaibe/howto#1]
It looks like letsencrypt.org is up and running since this article was last updated and I just wanted to see if you could describe the differences in the steps involving server/client certificates if I were to use a real certificate, for example issued to my own domain name.

If I received certificates from letsencrypt.org would they be in PEM format? Would I copy it both to my server and to my clients and then also repeat the process for every 90-day renewal?

**Comment by ouaibe** [comment]
Excellent question. I was planning on doing an update when I have time to migrate to letsencrypt from my current CA. No ETA though, probably some time this summer.

If you're in a hurry, you're more than welcome to test the process and do a pull request with the new info.

**Comment by chepurko** [comment]
Sure I can try putting something together, but I'm stuck near the end with client certificates. I've already authenticated my domain with Let's Encrypt and have generated keys (there is a chain of keys, so a key for my server and a key for the intermediate CA) which are all just PEM files.

The root CA key should then be taken care of on Androids via the pre-installed DST Root CA X3 (cross-signed Let's Encrypt cert.). But I don't know where to get a client certificate for an Android client, for example. Do I have to use the `openssl` commands which are in [5) Manage Client Certs.](https://github.com/ouaibe/howto/blob/master/OpenWRT/802.1xOnOpenWRTUsingFreeRadius.md#5-manage-client-certs)? Should I be able to generate client certs. using the [DST Root CA X3](https://www.identrust.com/certificates/trustid/root-download-x3.html) (or [ISRG Root X1](https://letsencrypt.org/certificates/) which is not in the default Android key store)?

Certificates are hard! :)

**Update:** I'm starting to think that maybe using real certs. with EAP-TLS isn't possible since the CA (in this case Let's Encrypt) must be the one signing the client certs., not you yourself. Since with Let's Encrypt you only get a server cert. and a CA cert. then maybe you can only do other EAP protocols like PEAP, for example. Correct me if I'm wrong, of course.

**Comment by chepurko** [comment]
One other thing I'm unsure about is whether [the code](https://github.com/ouaibe/howto/blob/master/OpenWRT/802.1xOnOpenWRTUsingFreeRadius.md#3-configure-freeradius-on-openwrt) supports certificate chains, which Let's Encrypt gives you (mentioned in my previous post). I.e. `private_key_file = ${certdir}/server.pem`.

You actually get a `cert.pem` for your server, a `chain.pem` for the intermediary, and a `fullchain.pem` which includes both, the server and intermediary keys, from Let's Encrypt. I'm wondering if I should put the `fullchain.pem` file into `esp.conf` or just the `cert.pem`. Same thing goes for the client side, where there's a chain as well.

**Comment by chepurko** [comment]
FYI I've become more familiar with the official and [commercial Freeradius documenation](http://networkradius.com/doc/FreeRADIUS-Implementation-Ch6.pdf) and some implementation scenarios, and the documentation actually advises _against_ using a public CA like Let's Encrypt and instead using self-signed CAs (similar to how OpenVPN deployments work).

This is because an attacker can easily [pose as a fake RADIUS server](https://depthsecurity.com/blog/when-802-1x-peap-eap-ttls-is-worse-than-no-wireless-security) and just grab a public CA which is obviously available publicly or on many machines by default. The public CA may add a little convenience in that the CA may already be availble on the wireless client, but if the passwords are weak, for example, the attacker can just brute force user credentials after obtaining user names and challenge/response pairs.

Instead, I stuck to a more familiar environoment running native `freeradius` on a Raspberry Pi (package available on any Debian/Ubuntu install also) which includes the necessary `ca.conf`, `server.conf` and `client.conf` and `make` scripts in the `/usr/share/doc/freeradius/examples/certs directory` (instead of `raddb/certs`) to configure and create/sign your own certificates.

I'm not as familiar with the `freeradius2` packages in `opkg` so I'm not sure if the same `.conf` and `make` scripts are available in the OpenWRT versions. But if they're not available or if it's too fiddly doing it on a router one can just run the `freeradius` package on any Debian/Ubuntu install, create their own self-signed certs. and then transfer them over to their OpenWRT router.
